main: online.vitreusmc.vitreusSocial.VitreusSocial

name: VitreusSocial
version: 0.0.1
permissions:
  milestone.12:
    default: false
  milestone.24:
    default: false
    children:
      milestone.12: true
  admin:
    default: op
    children:
      milestone.24: true

commands:
  setplaytime:
    description: Sets a player's playtime statistic.
    usage: /setplaytime <PlayerName> <MinutesPlayed>
    permission: admin
  playtime:
    description: Print out your time played!
    usage: /playtime
    aliases: [time, mytime, played]
  color:
    description: Set your chat color!
    usage: /color <color>
    aliases: [dark_blue, blue, dark_aqua, aqua, red, gold, dark_gray, gray, black, green, dark_green, light_purple, white, yellow, dark_purple, dark_red]
    permission: milestone.12
  local:
    description: Chat locally!
    usage: /local on | /local <Message>
    aliases: [lc, l, localchat]
  global:
    description: Chat globally!
    usage: /global on | /global <Message>
    aliases: [gc, g, globalchat]
